language: node_js
node_js: '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mr.tu@michaelqq.com
  api_key:
    secure: HP8Qu5XPEsbvLaHK5RIbzGKyVZTBaS6ttdDt7oZWzrEZ3izW7Ky5Vq56OeK+4C+H4BYNrTouzde6n3hoBEpf2jGQJw62DRthBbWBqTmDaPh8aCvovBXgMf2Vst8JwmdG64SxOkquWlmpLYuucH4ky5l+FGlAT4JjE6u6G51cvC9oo8aD05QQf0J8latvJjROteVN62AJfgO9QSNxVPjTnUAaWX3r0jKQgTK26prYX0aLBccWJptHLCzbU6mlwGJr1zR7RxFa8qtqfOw3n49cxeZfCL2NJI4xBRbZNEnhL+xEtYQUltKYifMetwQ/XqxXeIVWP9ZdEKLt2/YAh1Hrh3n3PuGyvOIn5Serw2Jtj0ENOh2GNQm/hfK3l5wd2KrszLfUQalkQ60q8NsgGw68k2p3DjQNukS20qrBhe78jMvOwHiyuBI/PO1aE1zkbLwAIv5Y9ePcjzj64QGVDJyKvBkJExkTXvfTECnIi4Sjbmrgez4QawYB/KfxAnKiMpjtKRdXg3jyg2acT6j9/e/gvNiTjI5FCKOGIZ3iazBPUUYEVTlZuIM5VuZbnbJ4t4H9Cf0Jaf3A73UEig00Vdj50EB4ka7e2cBsXXrfU+tukqmKmU8HJR8lI+2yvIit9/pMr+J1qlY8yRn50LPKxj0vTJNxqoe+3tZEafqwefdPcLU=
  on:
    tags: true
    repo: MichaelQQ/dbfstream
